### ISSUE TITLE
Translate for your language

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/FireTODOList#1]
The original strings in english is in:
`res/values/strings.xml`

To trasnlate, duplicate the file, create a "value" folder for your language: `res/values-lang/strings.xml`
Where "lang" is your language!

**For example:**
res/values-fr/strings.xml contain French text for all the strings.
res/values-ja/strings.xml contain Japanese text for all the strings.

**You can suggest corrections too!!**

The APP is ready for:
- [x] Arabic
- [x] Belarusian
- [x] Bengali
- [x] Bulgarian
- [x] Catalan
- [x] Chinese - Mandarin
- [x] Croatian
- [x] Czech
- [x] Danish
- [x] Dutch
- [x] English
- [x] Finnish
- [x] French
- [x] German
- [x] Hindi
- [x] Hungarian
- [x] Indonesian
- [x] Italian
- [x] Malayalam
- [x] Norwegian
- [x] Philippines (Tagalog)
- [x] Portuguese
- [x] Polish
- [x] Romanian
- [x] Russian
- [x] Sinhala
- [x] Slovak
- [x] Spanish (Mexico)
- [x] Swedish
- [x] Turkish
- [x] Vietnamese
- [ ] Other Spanish avaliable (Please rename the folder with country too  e.g: "values-es-rES" for Spain )
- [ ] Any other language is avaliable!

**Comment by hashemmm96** [comment]
I'll translate to Swedish!

**Comment by Nubbin72** [comment]
I'll translate to Croatian

**Comment by vmmartinezlona** [comment]
I'll translate to Spanish c:

**Comment by KristofArron** [comment]
I'll do Dutch.

**Comment by atanasg** [comment]
I will translate to Bulgarian

**Comment by rodrigo-brito** [comment]
You are amazing guys!! Thanks for the contribution!

**Comment by atanasg** [comment]
@rodrigo-brito: I noticed that there is a typo in the English version: "Simple and useful tool for management of taks and reminders" (taks instead of tasks)

**Comment by rodrigo-brito** [comment]
it's wrong. I will correct here. Thank you @atanasg.

**Comment by gwenu** [comment]
I'll translate to Ukrainian

**Comment by tagniam** [comment]
I'll try to translate it into French!

**Comment by hndr91** [comment]
I will take Indonesian

**Comment by povesteam** [comment]
Adding Romanian translation

**Comment by paraschadha2052** [comment]
I will translate to Hindi

**Comment by atanasg** [comment]
I will also translate to German

**Comment by doficia** [comment]
Created Hungarian translation:
https://github.com/rodrigo-brito/FireTODOList/pull/16

Cheers!

**Comment by cmonfortep** [comment]
I will translate it to Catalan.

**Comment by bureken** [comment]
I will translate to Turkish.

**Comment by MilindaLaknath** [comment]
Hi @rodrigo-brito 

I will translate in sinhala.

**Comment by lcrosenbu** [comment]
I will translate to Finnish.

**Comment by pvtuan10** [comment]
I will translate it to Vietnamese.

**Comment by rodrigo-brito** [comment]
Thank you guys!

**Comment by crisbnk** [comment]
Hi @rodrigo-brito 
I'll translate it to italian.

**Comment by eternalBlast** [comment]
Can i still contribute to translate to Indonesian? @rodrigo-brito

**Comment by rodrigo-brito** [comment]
We have Indonesian @eternalBlast, but you can suggest corrections.

**Comment by MilindaLaknath** [comment]
@rodrigo-brito 

Hi,
Sinhala Translation added. #37. please check that.

Thank You.

**Comment by anikrajc** [comment]
@rodrigo-brito Translated to Malayalam! #39 

Thank you :)

**Comment by greystate** [comment]
Just added #40 with a translation to Danish 🚀

**Comment by AlexandreInsua** [comment]
I'll transtrate to portuguese...
Sorry. It's done.

**Comment by rodrigo-brito** [comment]
@AlexandreInsua, já temos a tradução para português do Brasil, o seu seria para qual país?

**Comment by AlexandreInsua** [comment]
Podo-a fazer para português europeu. Muda um bocadinho, mas só um bocadinho
 :)

**Comment by rodrigo-brito** [comment]
Ok! Muito obrigado!

**Comment by MNXANL** [comment]
I can translate to catalan :-)

**Comment by codegateau** [comment]
I will translate to Malay

**Comment by mariofelesdossantosjunior** [comment]
I will translate to Portuguese Brazil

**Comment by rodrigo-brito** [comment]
@mariofelesdossantosjunior o português brasileiro já está traduzido. 😄 
Mas pode rolar revisão também. Sugestões são sempre bem vindas!

**Comment by mariofelesdossantosjunior** [comment]
Sim fiz uma correção... no Português Portugal

**Comment by tuomount** [comment]
I'll do better Finnish translations. Current ones are not that fluent Finnish.

**Comment by bobharley** [comment]
I'll do Filipino

**Comment by balachandarsv** [comment]
Shall i do it for tamil?

**Comment by deatheguard** [comment]
I'm ready to translate to and from English, French, Ukrainian and Russian :)
Please notify me if you need my help.

**Comment by rodrigo-brito** [comment]
@deatheguard  thank you! You can suggest some corrections for the current translations if you prefer.

**Comment by Jorege98** [comment]
I'll add Galego

**Comment by Jorege98** [comment]
I'll do Valencian and Euskera  (Spanish languages)

**Comment by deatheguard** [comment]
@rodrigo-brito  I'd like to, just please provide me a link to the existing one in that case because I couldn't find it.

**Comment by rodrigo-brito** [comment]
The resource files are located at `app/src/main/res` folder.

**Comment by SachithMayantha** [comment]
I will it to Sinhala

**Comment by SachithMayantha** [comment]
I will translate it to Sinhala

**Comment by SachithMayantha** [comment]
Please notify me

**Comment by rodrigo-brito** [comment]
Hi @SachithMayantha, We don't have this translation yet. Feel free to contribute. Thank you!
